### ISSUE TITLE
error when node includes "."

### ISSUE THREAD

**Issue by audrey-b** [poissonconsulting/sims#15]
sims_simulate("y.x ~ dnorm(0,1)")
Error in rjags::jags.samples(model, variable.names = monitor, n.iter = 1L,  : 
  No valid monitors set
In addition: Warning message:
In FUN(X[[i]], ...) : Failed to set trace monitor for x
Variable x not found

**Comment by joethorley** [comment]
OK thanks - the . in the name is causing problems - I'll look into it early next week

**Comment by joethorley** [comment]
fixed
