### ISSUE TITLE
Monitors in sims_simulate

### ISSUE THREAD

**Issue by audrey-b** [poissonconsulting/sims#29]
So far, each time I've used sims_simulate in an application, I always end up having to tweak to latent=NA, stochastic = NA and set monitors manually to get the nodes I want. This is because in a lot of models some of the latent variables are actually observed; and also we may be observing a transformation of a random node (i.e. deterministic nodes). I think that from a practical point of view, it would make more sense to set the default to latent=NA and stochastic = NA. This way one can simply set monitor= to whatever they need. Otherwise, an error message is thrown out when trying to set monitors to a different subset of nodes than the one reported by default. I find that it is not intuitive to have to change latent=NA and stochastic = NA to get the desired result and that could deter users.

On the other hand, with very simple models that do not have latent variables (e.g. a regression model), having latent=NA and stochastic = NA by default would produce the same results as the current setup. 

Thoughts?

**Comment by joethorley** [comment]
The distinction is kind or arbitrary from a true Bayesian perspective (data are just observed parameters) which fits with your practical experience. Do you think we should get rid of latent and stochastic entirely?

**Comment by joethorley** [comment]
@audrey-b - I don't have time to address for the foreseeable future - feel free to explore in a branch.
