### ISSUE TITLE
should we be calling the package sims?

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/sims#8]
The main function sims doesn't have any priors in it plus it would be good to analyse using ML as well. Should we be calling the package sims?

**Comment by audrey-b** [comment]
Oh wow, that name isn't taken! https://cran.r-project.org/web/packages/available_packages_by_name.html
That would be a nice - short - easy to remember - general name.

**Comment by joethorley** [comment]
OK let's go for it - I'll make the change as it will help focus development

**Comment by joethorley** [comment]
done
