### ISSUE TITLE
reproducible when a simulation fails

### ISSUE THREAD

**Issue by audrey-b** [poissonconsulting/sims#9]
We have to make sure we save to file the random generated numbers in case we need to go back to redo an analysis if an analysis fails, or if the script crashes.
So basically, when calling sims_run, I think we should first create files with random numbers within each subfolders. Then, before doing an analysis, the number is read and used to generate inits.

**Comment by joethorley** [comment]
I like the idea of saving the seeds.

**Comment by joethorley** [comment]
done
